spring.application.name=kbc-appointment-service
server.port=8083

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/kbc-dev
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=appointment
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=8d4f0c1115bbcbe78116f429c8fb75a1fc78c566cf66b2b1159c8916a15e3b8fa5289458370bbfdefb6e80ee77d2a5cd2c8fab32307659326cdb0148c9790447
jwt.expiration=3600000
