spring.application.name=kbc-appointment-service
server.port=8083

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/kbc-dev
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=appointment
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
